# Generated by Django 3.0 on 2019-12-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_path', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
    ]
