# Generated by Django 3.0 on 2019-12-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='custom_sounds/'),
        ),
    ]
